# Generated by Django 3.0.5 on 2021-05-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_email', models.CharField(max_length=30)),
                ('mem_pw', models.CharField(max_length=15)),
                ('mem_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_ticker', models.CharField(max_length=30)),
                ('stock_price', models.IntegerField(default=0)),
                ('stock_talk', models.CharField(max_length=1000000)),
                ('stock_date', models.DateTimeField(verbose_name='date published')),
                ('stock_emo', models.CharField(max_length=15)),
            ],
        ),
    ]
